### ISSUE TITLE
Log WP_DEBUG errors to file

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-skeleton#11]
It would be a lot easier from a development point of view of errors were logged to file when in development mode. 

Therefore, the relevant constants to enable logging need to be added to the `local-config.php` file to facilitate this.

**Comment by mwtsn** [comment]
@davetgreen kapow core does this a little. I'll show you shortly.

**Comment by davetgreen** [comment]
@mwtsn Going to close this as Kapow Core does exactly what I wanted to introduce.
