### ISSUE TITLE
Additional WP-CLI commands?

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-skeleton#21]
We may be able to save a few minutes in each build by automating some common tasks. Looking at the WP CLI documentation we have a few possible options.

`wp import`
We could import test data immediately, whether it be something like WP Test, or dummy data of our own.

`wp option`
There are several options such as permalink structure, setting the sample page as the homepage etc that get set on every build that we could easily automate?

`wp plugin`
Do we start adding some commonly used plugins to every build right at the very beginning?

@mwtsn penny for your thoughts sir?

**Comment by mwtsn** [comment]
Many of the image manipulation and compression plugins are common, and the DB Sync stuff.

I think we should import the theme test stuff too.

**Comment by davetgreen** [comment]
@mwtsn cool, I'll draw up a shortlist when I get to this ticket. Agree with the theme testing data as well. Can pull it down each time.

**Comment by davetgreen** [comment]
`wp option update permalink_structure '/%postname%'`

`wp option update show_on_front 'page'`
`wp option update page_on_front 2`

**Comment by davetgreen** [comment]
Automatically import this: https://raw.githubusercontent.com/poststatus/wptest/master/wptest.xml

`curl -O https://raw.githubusercontent.com/poststatus/wptest/master/wptest.xml`
`wp import wptest.xml --authors=skip`

**Comment by davetgreen** [comment]
@mwtsn just implementing the above now. I'm going to leave plugins for now with the exception of automatically activating Kapow Core.

Think a discussion ticket is needed to flesh out what (if any) other plugins we want to automatically install/activate.

**Comment by davetgreen** [comment]
Completed.
