### ISSUE TITLE
Do not store Databases in the Git Repository

### ISSUE THREAD

**Issue by mwtsn** [mkdo/kapow-skeleton#6]
Based on the discovery of this issue: https://github.com/mkdo/knowledge-base/issues/6 GitHub rejects repositories that contain large files.

Other methods such as DB Sync can be used.

**Comment by davetgreen** [comment]
@mwtsn closing as PR merged. Vagrantfile is where the magic is to export these databases, guess that's now something that Kimb and I should pull out.
