### ISSUE TITLE
Consider location of functional JS

### ISSUE THREAD

**Issue by mwtsn** [mkdo/kapow-skeleton#8]
Non-theme based JS functions should be removed from the Theme aspect of Kapow, and placed within a core plugin. These should be compiled into a single JS file within the plugin and optionally included in the main build via the Gruntfile.

For example the clickjack prevention JS.

**Comment by davetgreen** [comment]
@mwtsn anything in the theme right now that you'd consider to be non-theme based? I think we're fairly safe for that out of the box?

**Comment by mwtsn** [comment]
Just the one I mentioned above really @davetgreen

**Comment by davetgreen** [comment]
@mwtsn closing this as doesn't require any work on the Skeleton as it stands.
